### ISSUE TITLE
Collusion

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#1]
Add regulations against collusion in both the MTR and IPG Addendums

Inspiration: https://docs.google.com/document/d/10Sf3yDoIZmVr0PQ8f9vVwqJnXkiqL9UnVJsq2cPWuIw/edit

**Comment by fbatista** [comment]
Current state:

- No specific regulation for collusion.
- Allow for tournament-specific code-of-conduct to define what's acceptable behaviour.
- Some regulation that minimizes the potential for abuse.

---

Proposal

Introduce the following in the rules:

> **Collusion, Kingmaking and Spite Plays**
> In game theory, a “kingmaker” is a Player who lacks sufficient resources or position to win at a given game, but possesses enough remaining resources to decide which of the remaining viable Players will eventually win.
>
> One element of a multiplayer format is that Players can take game actions that allow other Players to win accidentally.
>
> Judges will not regulate suboptimal gameplay.
>
> If you believe a Player is “king’s making”, colluding with another Player, or performing a “Spite Play”, please call a Judge.
>
> These constitute a violation of the code of conduct and will be treated as such. Collusion in particular is a very serious offense.
>
> Players may not use this anti-kingmaking policy to abuse their opponent’s position as a shield to attempt to win, for example:
> - Player A has a win attempt, Player B has a win attempt that Player A knows about and Player C only has one answer to stop A or B but not Both. In this situation, Player A cannot just try to win and use the argument that if Player C uses their answer, it would be kingmaking.
>
> Keep in mind that sometimes a Player might seem to be performing a “kingmaking” or “spiteplay” decision, when in reality that line of play is the one that favors them most in the tournament progression, for example:
> - During Swiss rounds, Player A presents a win, Player B has a Pact of Negation with no mana to pay for the trigger on their next upkeep. However Player B believes that by stopping Player A they might have a chance that the game ends in a draw therefore resulting in them gaining 1 point instead of 0.
> - Player A presents a win, and they have Force of Will that Player B saw in a previous turn via Gitaxian Probe, Player B has a Pact of Negation, with no way to pay for the trigger in the next upkeep, but Player B suspects that Player C has interaction. Because Player B is the first to respond, they must play the Pact of Negation so that Player A uses their Force of Will and then allows Player C to effectively counter the win.

**Comment by purplejudge** [comment]
This is pretty much what we had written before, and I feel like it holds up. Maybe we should add more examples as to what we would consider and not consider kingmaking? This is by far the most dubious part of the Multiplayer policy and it usually shows up in very important parts of our tournaments. It's probably best we strive to have it as clear as possible

**Comment by fbatista** [comment]
So the plan is to add these situations under the unsporting conduct of the MTR and reference them in the IPG - Unsporting Conduct section.

Spite play would fit under unsporting conduct - minor
Collusion should probably have it's own section with disqualification as a penalty

Above we have examples for when it's not spite play.

I'll craft examples for when it is spite play and also examples of what is collusion and what is not.

**Comment by fbatista** [comment]
Player communication as a vehicle for collusion is also something we need to address:

- In a Multiplayer-Free-for-all tournament, Players shouldn't be allowed to secretly exchange information with one another.
