### ISSUE TITLE
Points per win changes

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#15]
## Introduction

In 1v1, the average win rate is 50%, not counting draws. When we calculate the tiebreakers we use a minimum of 33% win rate for opponents. Looking at how this relates to the point distribution, in 1v1 a win is worth 3 points and a draw is worth one point, so the 33% corresponds to the ` draw_points / win_points ` (FYI, topdeck.gg doesn't do this currently...)

In multiplayer the average win% is 25%.
Right off the bat, it makes no sense to use 33% as the minimum win rate for opponents, since that’s already above the average.
Using the same formula and 5 points per win, we reach a value of 1/5 = 20%. But that’s still way to high if we do a relative comparison between the 1v1 and 4ffa: 
50% => 33% in 1v1
25% => 20% in ffa

## Proposal

So I was thinking we should change the points per win to 7. Why 7? Because:
It would make the minimum win% be 14.28% which looks much more interesting when put into perspective:
50% => 33%
25% => 14.28%

And also, if we think about the incentive to win the game, since the average chance is 25%, as it’s much more difficult to win a game than in 1v1, then the reward should be proportionally higher.

Over 8 rounds, an average player that wins 50% of their games (no draws) in 1v1, gets 12 points.
A player that draws all games in 8 rounds gets 8 points. This makes “playing to win”, with a 50% chance, yield 50% more points than playing to draw.

Same thing with 4ffa now:
Over 8 rounds an average player that wins 25% of the games wins 2 games, with 5 points per win, that’s 10 points, while a player that draws all games, makes 8 points. So the player that played to win in this case only got 25% more points

Now let’s do the math with 7 points:
8 rounds, 14 points vs 8 points: this gives the player that played to win 75% more points, which feels better since the reward should be inversely proportional with the chance to win. (High risk high reward)

(With 6 points we make the reward be 50% instead, but I think that if the chance to win is lower, then the reward should be higher, thus I believe 7 points is better than 6)

## Q/A

> But 5 or 7 are not objective boundaries and it's of course one of the fundamentally difficult to answer questions in such systems. How many draws should be 1 win?
4 feels 100% too low.
But I'm not sure if it should be 5 or 7 in that regards.
But like I said and I think the more important part here is, that we do not care about these specific players anyways.
With 5 rounds, no one with 1 win or 5 draws will make top cut.
With 6 rounds, you can have players with 2 wins and players with 1 win and 5 draws. Neither of them will make top cut. 

It's not about the 5 or 7, its about the effort vs reward ratio. 7 happens to be the number that fullfills the ratio better
lets say that a win is worth 2 points and a draw worth 1 point
since your chance to get a win is 25% (not counting for draws or turn order) , then in 4 rounds you get an average of 2 points
if you draw all of those rounds, (which is the win% we use in 1v1, for the opponent's min win %) then you get a negative ratio, or a negative expected value when playing a win vs drawing a game.
same is true for 3 points per win
with 4 points per win, you an equal ratio
with 5 points per win you get a +25% ratio
with 6 points it's +50% ratio
and 7 points is +75% ratio
in 1v1, your avg chance to win being 50%, with 3 points win and 1 point draw, the ratio is also set at +50%
since in 4 ffa it's much more difficult to win a match, (25% vs 50%) it makes sense that the reward ratio is higher than 50%
so if we scale the reward % inversely with the average win%
then if the win % is 25% then the reward ratio should be 75%
hence 7 points per win

> So it would now be more interesting to hear, what potential upsides you see, given an appropriate oppo win % floor (i.e. draw_points/win_points)

As we now find a more accurate reward system for wins, we can then more effectively classify your opponent's performances, since playing against opponents that win matches is better than playing against opponents that draw matches, further disincentivizing Intentional Draws.

**Comment by purplejudge** [comment]
There's a lot to like here, and I overall support this change.

The only wrinkles I can see right off the bat are:

1) As intended, this makes getting a win that much stronger, which means any one win may be enough to push a player into the playoff portion of the event. This doesn't feel great, especially with byes involved. As we are also looking into removing those, this is less of an issue. Still, it feels weird that a player might win their first round against random opponents, never win again for the rest of the tournament, and still make it into the top portion of the event.

2) This might (will?) make it so players are less inclined to ID matches during the Swiss rounds, which is overall worse for the tournament (they take more time, reach stalemates, go into extra turns...). Have you had any player feedback regarding this possible change?

**Comment by fbatista** [comment]
In response to your concerns, @purplejudge:

- The tests that we did so far worked fine, and in small events, the only noticeable difference would be when calculating the OMW% (which we can't control atm due to topdeck.gg). 

- In large events, with 6+ rounds, the difference will be quite small, since typically the cut (with 5 points per win) is around 2 wins + 1 or 2 draws. With the 7 points per win, we don't really change the dynamic that much, but we do emphasize that a win might be worth it for you to play for it than to just play for a draw. 

- Ultimately your concern regarding intentional draws is real, however, a draw is still worth more than a loss: "infinitely more" because a loss is zero :P Thus players that are facing a losing situation will still prefer to draw. I think that this change will just make it so that your initial plan (before reaching the stalemate section of the game) is less focused on drawing / stalling and more focused on winning!

**Comment by fbatista** [comment]
Thus said, I'm ready to release the 7 point changes soon. We just need to coordinate with the organizers and let them know this is coming :)
