### ISSUE TITLE
Round time

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#3]
Evaluate if we need to perform changes to the Round time, where 90 minutes without extra turns might be not the best solution.

**Comment by fbatista** [comment]
the 90 minute timer without extra turns better for the organizers since round times are more predictable, although i've seen games still go beyond the 90 minute mark by more than 40 minutes due to a combination of deck check where sleeves had to be swapped + a very long last turn.

So all in all, the tournament organizer benefit is kind of limited, and for the players, having the chance to play one more turn after the time runs out, definitely results in less draw % overall. 

Not to mention that the potential for stalling is quite bigger when there are no extra turns, since the additional remedy for slow play can't be applied (which would be to remove the extra turns from the player that commited the slow play infraction).

So yeah 90 minutes without extra turns is not so great for players...

**Comment by JimmyLang420** [comment]
this isnt my idea, 
but id like to try the idea @fbatista brought to me.
75min + 1 extra turn each + *extra turns allowed* + game ending on the end step of the turn its on after 15m of calling clock
that would allow decks like najeela turns and tivit seive to have a chance.
as the current 90m no extra turns just smothers these type of decks/gameplans

**Comment by FranciscoBarata21** [comment]
personally i think playing withouth extra turns immensely decreases the quality of the game for the players since a lot of times you will pass the turn with 40ish minutes on the clock and chances are you don't see another turn (even though attempts maybe have been made no one won the game) meaning you had a lot less time to play for a win and your best plan for the game becomes playing for a draw. I'm not saying getting to a point in a game where the best option is to play for a draw is a bad thing, but having this point come on as early as 45-50 minutes into the game is very very bad for the quality of the format. Extra turns are needed in order to stop this from happening. Since, from what i have seen this 40ish minute statistic is very realistic i would suggest we try a format of 65 minutes game + extra turns.

**Comment by acabaca24** [comment]
At the last pirate chest tournament, one of the players had a really nice suggestion.
We should separate the round time, from mulligan time. 

Maybe instead of 90 minutes per round, we should have 80 minutes per round and 15min to sit down players and resolve mulligans. This 15min timer could start as soon as the pairings are posted.

This way we insentivise players to show up earlier and start resolving mulligans as soon as possible.

Edit: this could even be applied with the extra turns rule. Making rounds instaead of being 75min + turns, 15min(seeting, shuffling, mulligan) + 60min(game time) + extra turns.

**Comment by fbatista** [comment]
> At the last pirate chest tournament, one of the players had a really nice suggestion. We should separate the round time, from mulligan time.
> 
> Maybe instead of 90 minutes per round, we should have 80 minutes per round and 15min to sit down players and resolve mulligans. This 15min timer could start as soon as the pairings are posted.
> 
> This way we insentivise players to show up earlier and start resolving mulligans as soon as possible.
> 
> Edit: this could even be applied with the extra turns rule. Making rounds instaead of being 75min + turns, 15min(seeting, shuffling, mulligan) + 60min(game time) + extra turns.

I like the idea of separating the mulligan time, because it's a best of 1 match (which makes mulligans more important) and it's a 100-card deck (which is harder to shuffle).

**Comment by fbatista** [comment]
> > At the last pirate chest tournament, one of the players had a really nice suggestion. We should separate the round time, from mulligan time.
> > Maybe instead of 90 minutes per round, we should have 80 minutes per round and 15min to sit down players and resolve mulligans. This 15min timer could start as soon as the pairings are posted.
> > This way we insentivise players to show up earlier and start resolving mulligans as soon as possible.
> > Edit: this could even be applied with the extra turns rule. Making rounds instaead of being 75min + turns, 15min(seeting, shuffling, mulligan) + 60min(game time) + extra turns.
> 
> I like the idea of separating the mulligan time, because it's a best of 1 match (which makes mulligans more important) and it's a 100-card deck (which is harder to shuffle).

After some further thought...

Players are already free to make mulligan decision before the clock starts, so technically we would just be formalizing a "hidden" rule, and **allocating a specific amount of time for that**. 

Now this raises a couple of issues: 
- How would we deal with players that mulligan down to 4, compared with players that kept the first seven ?
  - Do we expect both of them to spend whole 10 minutes shuffling and making mulligan decisions?
    Seems like the pod that kept the first 7 will just be bored waiting for the 10 minute mark to pass by.
At the same time, the pod with players mulligan down to 5 / 4 will be hard pressed to keep because the 10 minutes timer is running out.
  
- What happens if the allocated time for mulligan ends?
  One nice thing is that by having a specific timer we could issue tardiness penalties.
  In the current system, we CAN already issue slow play penalties for players taking too long to mulligan...

**Comment by fbatista** [comment]
Idea A: ❤️ 

- Round time 80 minutes
- 1 extra turn per player still "alive"
- Players have at most 10 minutes to make all the mulligan decisions after the clock starts, otherwise they incur in Tardiness.
- Slow play warning has an additional remedy of having the perpetrator skip ALL extra turns granted by the End of Round procedure. (as of now)
- Tardiness warning has an additional remedy of having the perpetrator skip their first turn. (as of now)
- Each extra turn players take during End of Round is capped at 5 minutes. If the 5 minutes run out, the player simply passes priority on everything until their cleanup step. (5 x 4 = 20 minutes maximum)
- Allow for loops that involve extra turns to be presented and executed, and taking an extra turn in the context of a loop doesn't count for the (4) extra turns from the end of round procedure.

---

Idea B: 😄 

- Same as above except: there is no individual time cap on the extra turns, instead there is a 20 minute total time limit for all the extra turns; The game continues until the end of the current AP's turn, whoever that player is.

---

Idea C: 🎉 

- Same as above, except: the game ends abruptly after the 20 minutes in a draw, no matter what is on the stack.

---

Pros and cons:
- A seems to more evenly distribute the time across players, however, it disregards the time NAPs take during AP's turn.
- If we're giving 20 minutes extra time, why not make it 100 minutes total time? 
- Ending a game abruptly can create feels bad situations where a player might be performing a actions that aren't being shortcut but ultimately lead to a win.


**NOTE**: The times mentioned above are subject to being adjusted:
- 60~80 minutes round time.
- 5~10 minutes mulligan time.
- 15~20 minutes End of Round extra turns time.

**Comment by purplejudge** [comment]
I think we're walking in the right direction with this one, but I feel like we still need to iron out some things.

Personally, and even though we've never done any statistics for this, I feel like most games that go into EoY end as draws anyway. I understand this policy can be quite annoying for players who see a way for them to win if they had the extra turns, but a lot of the time, the extra turns just lead to everyone present waiting 30+ minutes for a result we knew would come: draw.

However: player satisfaction is very important. I would say probably more important than statistics (and that's saying a lot, coming from me!). If the general feeling is that extra turns would be better, then that's what we'll do.

That creates all sorts of problems, however. Extra turns can take a looooooooooong time. Like, 40-minutes long. That's possibly half a round. However, if you cap it, are you really adding extra turns? Say we go with the shared 20 minutes, not the 4*5 minutes. What changed from the regular timer? It's like Fábio was saying: that's just a timer of 100 minutes with extra steps.

I like idea A the best. Yes, it also has problems, and we'll probably need to polish it further in the future. But as of right now, from the ones presented, I feel like it makes the most sense

**Comment by fbatista** [comment]
The linked Pull request introduced the change for the 75 + extra turns with a total 20 minute cap.

@purplejudge you were talking about option A, that has 80 + extra turns of 5 minutes each, and there is a forced "pass the turn" if that time expires.

My perspective is that this has more potential for "feels bad" moments, where you are dealing with a very complex win situation, and you are going as fast as possible, and if opponents just ask you questions to throw you off, they can severely break your thought process and abuse that to make you pass the turn once the 5 minutes are over.

The 75 + turns <= 20 solution for me creates an interesting dynamic:
- During regular time, players won't feel they "wont have another turn" even with 20 minutes on the clock, which is a feeling that happens now with the 90 minutes
- During extra turns, opponents of the active player will have a HUGE reason to make sure AP plays fast (because they want to play!), and that translates in a bigger motivation to call a judge on slow play.
- During the extra turns, the floor judge availability to control slow play is better.


I'm going to keep this Issue closed, and we can re-open it if we see the need for that.
