### ISSUE TITLE
Priority Bullying / General Blackmailing

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#5]
Sometimes during a match, the game state reaches a point where a player might feel like they have a hudge disadvantage if they are the first ones to interact. In this situation, it's normal to try to gain some value out of the situation by "sandbagging" your interaction.

Sandbagging is a totally legitimate and actually pretty good strategy, however, it comes with a risk: your opponents might simply not have interaction.

When that happens, after you passed priority, as a player you cannot ask an opponent to perform an action with the pretext of saving the game if they do. The reasoning is that if you are allowed to do that, then the opponent will have to comply in order to actually play the game to win. This is generally seen as unfair, and because of this, we want to make sure that players own their decisions, and the risk of sandbagging must be owned by the player that sandbagged, not by the opponents. Bullying an opponent into taking an action this way is unsporting conduct and thus the Rules should regulate that.

This type of bullying / blackmailing can also happen in a situation where a player is presenting a win while another one could win if that player is stopped, but only a third player actually has a way to stop the first one. This typically leads to a standoff situation, most likely solved by an Intentional Draw, if the players so desire. Otherwise the third player might choose to stop the first player and the second player then has the chance to try and win with an open field. In this situation, when proposing a draw, you can't threaten the opponents with sentences like "if you don't draw, then I do this and we both lose". That's unsporting conduct and thus the Rules should regulate that. 

Inspiration:

https://docs.google.com/document/d/10Sf3yDoIZmVr0PQ8f9vVwqJnXkiqL9UnVJsq2cPWuIw/edit#heading=h.qyf20ll5xhuu

https://docs.google.com/document/d/10Sf3yDoIZmVr0PQ8f9vVwqJnXkiqL9UnVJsq2cPWuIw/edit#heading=h.plf2arfmzlcp

**Comment by purplejudge** [comment]
Nothing to add. It makes sense, goes against the philosophy of Competitive REL in general, and leads to awkward situations among players. Feels like a good policy guideline.

I would add it to Unsporting Conduct - Minor as an example (if unintentional, of course), but if it's already there, all is good.

**Comment by fbatista** [comment]
Will do!
